# Get all users.
GET http://localhost:3000/api/users/
Content-Type: application/json


####
# Delete all users.
DELETE http://localhost:3000/api/users/
Content-Type: application/json



####
# Add new user
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "name": "Patryk",
  "password": "admin"
}

####
# Add new user with admin rights.
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "name": "a",
  "password": "a"
}


####
# Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "name": "Patryk",
  "password": "admin"
}

####
# Get user with specific id user info.
GET http://localhost:3000/api/users/5f578128fb2ffb466cab2ebe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjU3ODEyOGZiMmZmYjQ2NmNhYjJlYmUiLCJpYXQiOjE1OTk1NzAyNDF9.Bzsg6V09DdRHzy9gLmUFQD6vj69EufTxub9pFtT9YUE


####
# Delete specific user
DELETE http://localhost:3000/api/users/5f46adb8963c4e663410ee42ss
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjOTU0ZjhhNTFiODMyZjg3YWNhMmIiLCJpYXQiOjE2MDMzOTA5NDF9.c9CgmoN5k-IKpzOP58_63fXfVnsflIJP5Sj16adsMt8
####

####
# Update meals
POST http://localhost:3000/api/days/meals/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjOTU0ZjhhNTFiODMyZjg3YWNhMmIiLCJpYXQiOjE2MDMzOTA4MDZ9.-vFV6Otw3xDgdibooGEAwBmlDRQEJp2_v2xKiPr99qY

{
  "meals": {
    "products": [
      {
        "name": "Kurczak",
        "grams": 0
      },
      {
        "name": "Kanapka",
        "grams": 10
      }
    ],
    "caloriesSummary": null
  }
}
####
